--! \file rom_pkg.vhd
--! \author Charles Ancheta
--! @cond Doxygen_Suppress
library ieee;
use ieee.std_logic_1164.all;
use work.fysh_fyve.all;
--! @endcond

--! Autogenerated package containing the ROM.\n
package rom is
  constant rom_arr : mem_t (0 to ROM_NUM_WORDS-1) := (
    x"37210100",
    x"ef00001a",
    x"63000000",
    x"6b050000",
    x"67800000",
    x"b7050000",
    x"83a54533",
    x"83a50500",
    x"33d5a500",
    x"13751500",
    x"67800000",
    x"130101ff",
    x"23261100",
    x"23248100",
    x"23229100",
    x"b7040000",
    x"03a58433",
    x"b7150100",
    x"1384d5dc",
    x"93050400",
    x"ef00c00e",
    x"33058500",
    x"23aca432",
    x"8320c100",
    x"03248100",
    x"83244100",
    x"13010101",
    x"67800000",
    x"b7050000",
    x"23aca532",
    x"67800000",
    x"37050000",
    x"03254533",
    x"03250500",
    x"67800000",
    x"b7050000",
    x"83a54533",
    x"23a0a500",
    x"67800000",
    x"37060000",
    x"03260633",
    x"83260600",
    x"13071000",
    x"3315a700",
    x"63880500",
    x"33e5a600",
    x"2320a600",
    x"67800000",
    x"1345f5ff",
    x"33f5a600",
    x"2320a600",
    x"67800000",
    x"37060000",
    x"03264633",
    x"83260600",
    x"13071000",
    x"3315a700",
    x"63880500",
    x"33e5a600",
    x"2320a600",
    x"67800000",
    x"1345f5ff",
    x"33f5a600",
    x"2320a600",
    x"67800000",
    x"37050000",
    x"0325c532",
    x"03250500",
    x"67800000",
    x"9305f000",
    x"63eea500",
    x"13152500",
    x"b7050000",
    x"9385052a",
    x"3385a500",
    x"03250500",
    x"67800000",
    x"13050000",
    x"67800000",
    x"13060000",
    x"63000502",
    x"9316f501",
    x"93d6f641",
    x"b3f6b600",
    x"3386c600",
    x"13551500",
    x"93951500",
    x"e31405fe",
    x"13050600",
    x"67800000",
    x"130101ff",
    x"23261100",
    x"23248100",
    x"1315d501",
    x"1355a501",
    x"93f57500",
    x"33e5a500",
    x"13040508",
    x"13050400",
    x"eff01ff0",
    x"13050400",
    x"8320c100",
    x"03248100",
    x"13010101",
    x"67800000",
    x"130101ff",
    x"23261100",
    x"13058001",
    x"93050000",
    x"eff09fee",
    x"13059001",
    x"93050000",
    x"eff0dfed",
    x"1305a001",
    x"93050000",
    x"eff01fed",
    x"1305b001",
    x"93050000",
    x"eff05fec",
    x"13050000",
    x"93050000",
    x"eff05ff8",
    x"93052000",
    x"13050000",
    x"eff09ff7",
    x"93053000",
    x"13050000",
    x"eff0dff6",
    x"13051000",
    x"93051000",
    x"eff01ff6",
    x"13051000",
    x"93054000",
    x"eff05ff5",
    x"13052000",
    x"93050000",
    x"eff09ff4",
    x"13052000",
    x"93052000",
    x"eff0dff3",
    x"13052000",
    x"93053000",
    x"eff01ff3",
    x"13054000",
    x"93054000",
    x"eff05ff2",
    x"13054000",
    x"93055000",
    x"eff09ff1",
    x"13054000",
    x"93057000",
    x"eff0dff0",
    x"13055000",
    x"93053000",
    x"eff01ff0",
    x"13055000",
    x"93056000",
    x"eff05fef",
    x"13056000",
    x"93054000",
    x"eff09fee",
    x"13056000",
    x"93055000",
    x"eff0dfed",
    x"13056000",
    x"93057000",
    x"eff01fed",
    x"6ff01ff4",
    x"3f000000",
    x"06000000",
    x"5b000000",
    x"4f000000",
    x"66000000",
    x"6d000000",
    x"7d000000",
    x"07000000",
    x"7f000000",
    x"6f000000",
    x"77000000",
    x"7c000000",
    x"39000000",
    x"5e000000",
    x"79000000",
    x"71000000",
    x"10000000",
    x"00000000",
    x"017a5200",
    x"017c0101",
    x"1b0c0200",
    x"18000000",
    x"18000000",
    x"6cfeffff",
    x"3c000000",
    x"00440e10",
    x"48810188",
    x"02000000",
    x"14000000",
    x"34000000",
    x"8cfeffff",
    x"fc000000",
    x"00440e10",
    x"44810100",
    x"00000000",
    x"e4beadde",
    x"e8beadde",
    x"efbeadde",
    others => (31 downto 0 => '0')
    );
end package rom;
--! From binary file fysh/simple-matrix.hex
--! 	.text
--! 	.attribute	4, 16
--! 	.attribute	5, "rv32i2p1"
--! 	.file	"simple-matrix.fysh"
--! 	.globl	pixel                           # -- Begin function pixel
--! 	.p2align	2
--! 	.type	pixel,@function
--! pixel:                                  # @pixel
--! 	.cfi_startproc
--! # %bb.0:                                # %entry
--! 	addi	sp, sp, -16
--! 	.cfi_def_cfa_offset 16
--! 	sw	ra, 12(sp)                      # 4-byte Folded Spill
--! 	sw	s0, 8(sp)                       # 4-byte Folded Spill
--! 	.cfi_offset ra, -4
--! 	.cfi_offset s0, -8
--! 	slli	a0, a0, 29
--! 	srli	a0, a0, 26
--! 	andi	a1, a1, 7
--! 	or	a0, a1, a0
--! 	addi	s0, a0, 128
--! 	mv	a0, s0
--! 	call	fysh_gpio_write_all
--! 	mv	a0, s0
--! 	lw	ra, 12(sp)                      # 4-byte Folded Reload
--! 	lw	s0, 8(sp)                       # 4-byte Folded Reload
--! 	addi	sp, sp, 16
--! 	ret
--! .Lfunc_end0:
--! 	.size	pixel, .Lfunc_end0-pixel
--! 	.cfi_endproc
--!                                         # -- End function
--! 	.globl	main                            # -- Begin function main
--! 	.p2align	2
--! 	.type	main,@function
--! main:                                   # @main
--! 	.cfi_startproc
--! # %bb.0:                                # %entry
--! 	addi	sp, sp, -16
--! 	.cfi_def_cfa_offset 16
--! 	sw	ra, 12(sp)                      # 4-byte Folded Spill
--! 	.cfi_offset ra, -4
--! 	li	a0, 24
--! 	li	a1, 0
--! 	call	pin_mode
--! 	li	a0, 25
--! 	li	a1, 0
--! 	call	pin_mode
--! 	li	a0, 26
--! 	li	a1, 0
--! 	call	pin_mode
--! 	li	a0, 27
--! 	li	a1, 0
--! 	call	pin_mode
--! .LBB1_1:                                # %loop_cond
--!                                         # =>This Inner Loop Header: Depth=1
--! 	li	a0, 0
--! 	li	a1, 0
--! 	call	pixel
--! 	li	a1, 2
--! 	li	a0, 0
--! 	call	pixel
--! 	li	a1, 3
--! 	li	a0, 0
--! 	call	pixel
--! 	li	a0, 1
--! 	li	a1, 1
--! 	call	pixel
--! 	li	a0, 1
--! 	li	a1, 4
--! 	call	pixel
--! 	li	a0, 2
--! 	li	a1, 0
--! 	call	pixel
--! 	li	a0, 2
--! 	li	a1, 2
--! 	call	pixel
--! 	li	a0, 2
--! 	li	a1, 3
--! 	call	pixel
--! 	li	a0, 4
--! 	li	a1, 4
--! 	call	pixel
--! 	li	a0, 4
--! 	li	a1, 5
--! 	call	pixel
--! 	li	a0, 4
--! 	li	a1, 7
--! 	call	pixel
--! 	li	a0, 5
--! 	li	a1, 3
--! 	call	pixel
--! 	li	a0, 5
--! 	li	a1, 6
--! 	call	pixel
--! 	li	a0, 6
--! 	li	a1, 4
--! 	call	pixel
--! 	li	a0, 6
--! 	li	a1, 5
--! 	call	pixel
--! 	li	a0, 6
--! 	li	a1, 7
--! 	call	pixel
--! 	j	.LBB1_1
--! .Lfunc_end1:
--! 	.size	main, .Lfunc_end1-main
--! 	.cfi_endproc
--!                                         # -- End function
--! 	.section	".note.GNU-stack","",@progbits
--! ></*>
--! Simple 8x8 matrix!
--! C1 - JE1 - gpio[24]
--! C2 - JE2 - gpio[25]
--! C3 - JE3 - gpio[26]
--! R1 - JE4 - gpio[27]
--! R2 - JE5 - gpio[28]
--! R3 - JE6 - gpio[29]
--! EN - JE7 - gpio[30]
--! 
--! Buttons:
--! H - gpio[0]
--! J - gpio[1]
--! K - gpio[2]
--! L - gpio[3]
--! 
--! o x o o x x x x
--! x o x x o x x x
--! o x o o x x x x
--! x x x x x x x x
--! x x x x o o x o
--! x x x o x x o x
--! x x x x o o x o
--! x x x x x x x x
--! 
--! (0,0), (0,2), (0,3), (1,1), (1,4), (2,0), (2,2), (2,3)
--! 
--! <*/><
--! 
--! >(pixel) ><row> ><col>
--! ><>
--!    (+o  (><{°> << ><{{{°>) | ><//> Output enable
--!         ((><row> & ><{{{°>) << ><{{°>) | ><//> Row is next higher 3 bits
--!         (><col> & ><{{{°>) ~ ><//> Col is first 3 bits
--! <><
--! 
--! ><//> It's little endian somehow so we gotta start at 24
--! ><//> Set buttons as input
--! [><{{(((°> >(pin_mode) ><(°>] ~
--! [><{{(({°> >(pin_mode) ><(°>] ~
--! [><{{({(°> >(pin_mode) ><(°>] ~
--! [><{{({{°> >(pin_mode) ><(°>] ~
--! 
--! ><//> TODO: Buttons
--! 
--! ><(((@> [><{°>] ><//> 1
--! ><>
--!    [><((°> >(pixel) ><(((°>] ~ ><//> 0 0
--!    [><((°> >(pixel) ><({(°>] ~ ><//> 0 2
--!    [><((°> >(pixel) ><({{°>] ~ ><//> 0 3
--!    [><({°> >(pixel) ><(({°>] ~ ><//> 1 1
--!    [><({°> >(pixel) ><{((°>] ~ ><//> 1 4
--!    [><{(°> >(pixel) ><(((°>] ~ ><//> 2 0
--!    [><{(°> >(pixel) ><({(°>] ~ ><//> 2 2
--!    [><{(°> >(pixel) ><({{°>] ~ ><//> 2 3
--! 
--!    [><{((°> >(pixel) ><{((°>] ~
--!    [><{((°> >(pixel) ><{({°>] ~
--!    [><{((°> >(pixel) ><{{{°>] ~
--!    [><{({°> >(pixel) ><({{°>] ~
--!    [><{({°> >(pixel) ><{{(°>] ~
--!    [><{{(°> >(pixel) ><{((°>] ~
--!    [><{{(°> >(pixel) ><{({°>] ~
--!    [><{{(°> >(pixel) ><{{{°>] ~
--! <><
--! 
--! ><//> we're just being nice to LLVM
--! ><(°> ~
